services:

  guia_lol-logger:
    build: .
    container_name: guia_lol-logger
    ports:
      - "3002:3002"
    env_file: .env
    networks:
      - guialolnetwork

networks:
  guialolnetwork:
    external: true
