<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin

namespace logger\ErrorLog\Base;

use Magrathea2\MagratheaModelControl;

class ErrorLogControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "logger\ErrorLog";
	protected static $modelName = "ErrorLog";
	protected static $dbTable = "logger_errors";
}
