<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin

namespace logger\Log\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class LogBase extends MagratheaModel implements iMagratheaModel {

	public $id, $service, $environment, $data, $timestamp, $occurred_at;
	// not columns: CreateInsertQuery() always writes these two, so they're declared to avoid dynamic properties
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "logger_logs";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["service"] = "string";
		$this->dbValues["environment"] = "string";
		$this->dbValues["data"] = "text";
		$this->dbValues["timestamp"] = "datetime";
		$this->dbValues["occurred_at"] = "datetime";
	}

	public function GetControl() {
		return new \logger\Log\Base\LogControlBase();
	}

	// >>> relations:

}
