<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin

namespace logger\Log\Base;

use Magrathea2\MagratheaModelControl;

class LogControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "logger\Log";
	protected static $modelName = "Log";
	protected static $dbTable = "logger_logs";
}
